version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.20 # Node 16 to match local environment
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Install Packages with npm
          command: npm install
      - run: mkdir -p ~/junit # Create the junit directory
      - run:
          name: Run Tests with Split Timing
          command: |
            # Capture test files and split them by timing
            TEST_FILES=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
            npm test $TEST_FILES
      - run:
          name: Copy JUnit Report
          command: cp ./junit/junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  build-and-test:
    jobs:
      - build-and-test
